---
# This workflow will validate the Kong decK state file and deploy
# the application to a target environment

name: Deploy

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths-ignore:
      - '**.md'  # All markdown files in the repository
  release:
    types: [released]

jobs:
  validate:
    uses: 18F/identity-idva-api-gateway/.github/workflows/validate-config.yaml@main

  deploy:
    if: github.repository_owner == '18F'
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: 18F/identity-idva-cf-setup@v2
        id: cf-setup
        with:
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
          cf-org: ${{ secrets.CF_ORG }}

      - name: Deploy application
        run: cf push
          --vars-file vars.yaml
          --var ENVIRONMENT_NAME=${{ steps.cf-setup.outputs.target-environment }}
          --strategy rolling

      - name: Apply CF Network Policies
        run: |
          cf add-network-policy kong sk-api
