---
# This workflow will validate the Kong decK configuration file

name: Validate-Config

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'  # All markdown files in the repository
  pull_request:
    # Only run the config validation if the config file has changed in a pull
    # request. Don't add this to the push->branches->main section, as we still
    # want pushes to the main branch to trigger a deployment whether the config
    # changed or not. 
    paths:
      - 'kong.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install decK CLI
        run: |
          brew tap kong/deck
          brew install deck
          deck version

      - name: Validate the Kong config file
        run: |
          deck validate
