---
# This workflow will validate the Kong decK configuration file

name: Validate-Config

on:
  pull_request:
    # Only run the config validation if the config file has changed in a pull
    # request. Don't add this to the push->branches->main section, as we still
    # want pushes to the main branch to trigger a deployment whether the config
    # changed or not.
    paths:
      - 'kong-config.yaml'
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install decK CLI
        run: |
          brew tap kong/deck
          brew install deck
          deck version

      - name: Validate kong.yaml
        run: |
          export ENVIRONMENT_NAME=dev
          envsubst < kong-config.yaml > kong.yaml
          deck validate --state kong.yaml

      - name: Install Kong
        run: |
          echo "deb [trusted=yes] https://download.konghq.com/gateway-2.x-ubuntu-$(lsb_release -sc)/ default all" | sudo tee /etc/apt/sources.list.d/kong.list 
          sudo apt-get update
          sudo apt install -y kong

      - name: Validate kong.conf file
        run: kong check ./kong.conf
