---
# This workflow will run a series of penetration tests against the GIVE API Gateway

name: Zap-Scan

on:
  workflow_run:
    workflows: ["Deploy-Dev"]
    branches: [main]
    types: [completed]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the API Gateway
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          target: "https://give-dev-test-pfs.app.cloud.gov"
